drop table if exists "stats";

create table "stats"
(
    id bigint generated by default as identity primary key,
    app varchar(255),
    ip varchar(255),
    "timestamp" timestamp,
    uri varchar(255)
);